import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-white  border border-gray-200 ">
          <div className="max-w-[1200px] mx-auto p-0 ">
            <div className="navbar flex justify-between bg-base-100 p-0">
              <div className="">
                <div className="dropdown flex ">
                  <ul className="menu-compact dropdown-content mt-8 p-2 shadow bg-base-100 rounded-box w-52 text-md font-bold font-specially uppercase">
                    {/* {menuItems} */}
                  </ul>
                  <label className=" lg:hidden md:hidden">
                    {/* <HiMenuAlt1 className="text-3xl bg-accent text-white font-bold p-1  rounded"></HiMenuAlt1> */}
                  </label>
                </div>

                {/* Logo Insert Here */}
                <div className="md:ml-0 ml-5">
                  <Link href="/" className="  flex items-center">
                    <h1 className="   md:text-2xl sm:text-xl text-lg font-bold text-primary  ">
                      Creative University
                    </h1>
                  </Link>
                </div>
              </div>
              <div className=" hidden lg:flex md:flex">
                <ul className="lg-menu menu-horizontal flex items-center p-0 font-semibold   text-primary space-x-5">
                  <List />
                  <button className="btn btn-primary">test</button>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
